#!/bin/bash
##
## Запускает сервер баз данных.
##

set -e

# Задаём UID сервера и меняем владельца файлов БД.
if [[ "${FILE_OWNER_UID}" != "" && "$(id -u mysql)" != "${FILE_OWNER_UID}" ]]; then
    usermod --uid ${FILE_OWNER_UID} mysql
    chown mysql /var/lib/mysql
fi

if [[ "${MYSQL_ROOT_PASSWORD}" != "" && "${MYSQL_DATABASE}" != "" ]]; then
    docker-mysql-migrate &
fi

exec docker-entrypoint.sh "$@"
